spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydb
  datasource:
    url: 'jdbc:mysql://localhost:3306/userdb'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 'Admin#1234'
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
